apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sendy
    appid: sendy
  name: sendy
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sendy
      appid: sendy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sendy
        appid: sendy
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: sendy
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: dbhost
              name: sendy
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: dbuser
              name: sendy
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbpassword
              name: sendy
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: dbport
              name: sendy
        - name: HOST
          value: sendy.proudcity.com
        - name: TLS
          value: "true"
        - name: PHP_MEMORY_LIMIT
          value: 128M
        image: gcr.io/proudcity-1184/sendy:master.2
        imagePullPolicy: Always
        name: sendy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 800Mi
          requests:
            cpu: 10m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/secrets
          name: sendy
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sendy
        secret:
          defaultMode: 420
          secretName: sendy
